services:
  web:
    build: .
    command: gunicorn arcui.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./datasets/:/app/datasets/
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.db
